plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.birzum24.delivery'

    compileSdk 35

    defaultConfig {
        applicationId 'com.birzum24.delivery'

        minSdk 24
        targetSdk 35

        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
            shrinkResources false

            proguardFiles 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.core:core:1.16.0'
    implementation 'androidx.webkit:webkit:1.13.0'

    // Google Location / GPS
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-messaging'
}
